/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/printers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Printers */
        get: operations["list_printers_api_printers_get"];
        put?: never;
        /** Create Printer */
        post: operations["create_printer_api_printers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers/ping-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping All
         * @description Ping every printer. Used by the admin page to render status badges.
         */
        get: operations["ping_all_api_printers_ping_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers/{printer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Printer */
        get: operations["get_printer_api_printers__printer_id__get"];
        /** Update Printer */
        put: operations["update_printer_api_printers__printer_id__put"];
        post?: never;
        /** Delete Printer */
        delete: operations["delete_printer_api_printers__printer_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers/{printer_id}/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description TCP-connect check. Fast (~2s timeout) and does not send any bytes.
         */
        get: operations["ping_api_printers__printer_id__ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_api_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template */
        get: operations["get_template_api_templates__template_id__get"];
        /** Update Template */
        put: operations["update_template_api_templates__template_id__put"];
        post?: never;
        /** Delete Template */
        delete: operations["delete_template_api_templates__template_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/halls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Halls */
        get: operations["list_halls_api_halls_get"];
        put?: never;
        /** Create Hall */
        post: operations["create_hall_api_halls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/halls/{hall_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Hall */
        delete: operations["delete_hall_api_halls__hall_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disciplines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Disciplines */
        get: operations["list_disciplines_api_disciplines_get"];
        put?: never;
        /** Create Discipline */
        post: operations["create_discipline_api_disciplines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disciplines/{discipline_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Discipline */
        put: operations["update_discipline_api_disciplines__discipline_id__put"];
        post?: never;
        /** Delete Discipline */
        delete: operations["delete_discipline_api_disciplines__discipline_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reasons */
        get: operations["list_reasons_api_reasons_get"];
        put?: never;
        /** Create Reason */
        post: operations["create_reason_api_reasons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reasons/{reason_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Reason */
        delete: operations["delete_reason_api_reasons__reason_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth-names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Auth */
        get: operations["list_auth_api_auth_names_get"];
        put?: never;
        /** Create Auth */
        post: operations["create_auth_api_auth_names_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth-names/{auth_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Auth */
        delete: operations["delete_auth_api_auth_names__auth_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/labels/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count */
        get: operations["count_api_labels_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/labels/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_labels_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan */
        post: operations["scan_api_import_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_import_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Imports */
        get: operations["list_imports_api_imports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Import
         * @description Delete the import and all labels attached to it.
         *
         *     Bulk-deletes labels first (single statement that hits the DB immediately),
         *     so by the time SQLAlchemy emits ``DELETE FROM import`` the FK has nothing
         *     to complain about. With ``PRAGMA foreign_keys=ON`` SQLite checks the
         *     constraint per-statement, so order matters here.
         */
        delete: operations["delete_import_api_imports__import_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cart */
        get: operations["list_cart_api_cart_get"];
        put?: never;
        /** Add To Cart */
        post: operations["add_to_cart_api_cart_post"];
        /** Clear Cart */
        delete: operations["clear_cart_api_cart_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Item */
        delete: operations["remove_item_api_cart__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/print": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Print All */
        post: operations["print_all_api_cart_print_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/print/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview
         * @description Render the same bitmap that would go to the printer, return PNG.
         *
         *     Pass either ``label_id`` (uses the discipline's template + label's text)
         *     or ``template_id`` + ``left_text``/``right_text``.
         */
        get: operations["preview_api_print_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/print": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Print */
        post: operations["submit_print_api_print_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History */
        get: operations["list_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin */
        get: operations["admin_admin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddRequest */
        AddRequest: {
            /** Sid */
            sid: string;
            /** Label Id */
            label_id: number;
        };
        /** AuthName */
        AuthName: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
        };
        /** Body_scan_api_import_scan_post */
        Body_scan_api_import_scan_post: {
            /**
             * Root
             * @description absolute path on the server to a Labels/ tree
             */
            root: string;
            /**
             * Wipe
             * @default false
             */
            wipe: boolean;
        };
        /** Body_upload_api_import_upload_post */
        Body_upload_api_import_upload_post: {
            /** Discipline Id */
            discipline_id: number;
            /** File */
            file: string;
        };
        /** CartItemDTO */
        CartItemDTO: {
            /** Id */
            id: number;
            /** Label Id */
            label_id: number | null;
            /** Discipline Name */
            discipline_name: string;
            /** Project Name */
            project_name: string;
            /** Data Hall Name */
            data_hall_name: string;
            /** Left Text */
            left_text: string;
            /** Right Text */
            right_text: string;
            /** Template Name */
            template_name?: string | null;
            /** Added At */
            added_at: string;
        };
        /** DataHall */
        DataHall: {
            /** Id */
            id?: number | null;
            /** Project Id */
            project_id: number;
            /** Name */
            name: string;
        };
        /**
         * Discipline
         * @description One discipline (subfolder with .xlsx in the original CLI layout).
         */
        Discipline: {
            /** Id */
            id?: number | null;
            /** Data Hall Id */
            data_hall_id: number;
            /** Name */
            name: string;
            /** Template Id */
            template_id?: number | null;
            /**
             * Color
             * @default FFFFFF
             */
            color: string;
        };
        /** DisciplineDTO */
        DisciplineDTO: {
            /** Id */
            id: number;
            /** Data Hall Id */
            data_hall_id: number;
            /** Name */
            name: string;
            /** Template Id */
            template_id: number | null;
            /** Template Name */
            template_name?: string | null;
            /** Printer Id */
            printer_id?: number | null;
            /** Printer Name */
            printer_name?: string | null;
            /** Color */
            color: string;
            /** Label Count */
            label_count: number;
        };
        /** DisciplineIn */
        DisciplineIn: {
            /** Data Hall Id */
            data_hall_id: number;
            /** Name */
            name: string;
            /** Template Id */
            template_id?: number | null;
            /**
             * Color
             * @default FFFFFF
             */
            color: string;
        };
        /** DisciplinePatch */
        DisciplinePatch: {
            /** Name */
            name?: string | null;
            /** Template Id */
            template_id?: number | null;
            /** Color */
            color?: string | null;
        };
        /**
         * HAlign
         * @enum {string}
         */
        HAlign: "LEFT" | "CENTER" | "RIGHT";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HallIn */
        HallIn: {
            /** Project Id */
            project_id: number;
            /** Name */
            name: string;
        };
        /** ImportDTO */
        ImportDTO: {
            /** Id */
            id: number;
            /** Discipline Id */
            discipline_id: number;
            /** Discipline Name */
            discipline_name: string;
            /** Data Hall Name */
            data_hall_name: string;
            /** Project Name */
            project_name: string;
            /** Filename */
            filename: string;
            /** Uploaded At */
            uploaded_at: string;
            /** Sheets */
            sheets: number;
            /** Rows */
            rows: number;
            /** Skipped */
            skipped: number;
        };
        /** PingResult */
        PingResult: {
            /** Printer Id */
            printer_id: number;
            /** Ok */
            ok: boolean;
            /** Ms */
            ms?: number | null;
            /**
             * Error
             * @default
             */
            error: string;
        };
        /** PrintAllRequest */
        PrintAllRequest: {
            /** Sid */
            sid: string;
            /**
             * Operator
             * @default
             */
            operator: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Clear After
             * @default true
             */
            clear_after: boolean;
        };
        /** PrintAllResult */
        PrintAllResult: {
            /** Ok */
            ok: number;
            /** Errors */
            errors: {
                [key: string]: unknown;
            }[];
            /** Log Ids */
            log_ids: number[];
        };
        /** PrintLog */
        PrintLog: {
            /** Id */
            id?: number | null;
            /**
             * Ts
             * Format: date-time
             */
            ts?: string;
            /**
             * Template Name
             * @default
             */
            template_name: string;
            /**
             * Printer Ip
             * @default
             */
            printer_ip: string;
            /**
             * Operator
             * @default
             */
            operator: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Left Text
             * @default
             */
            left_text: string;
            /**
             * Right Text
             * @default
             */
            right_text: string;
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Error
             * @default
             */
            error: string;
        };
        /**
         * PrintRequest
         * @description Either supply ``label_id`` (uses the discipline's bound template) OR
         *     ``template_id`` + ``left_text`` / ``right_text``.
         */
        PrintRequest: {
            /** Label Id */
            label_id?: number | null;
            /** Template Id */
            template_id?: number | null;
            /**
             * Left Text
             * @default
             */
            left_text: string;
            /**
             * Right Text
             * @default
             */
            right_text: string;
            /**
             * Operator
             * @default
             */
            operator: string;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** Printer */
        Printer: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
            /** Ip */
            ip: string;
            /**
             * Port
             * @default 9100
             */
            port: number;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** Project */
        Project: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
        };
        /** ProjectIn */
        ProjectIn: {
            /** Name */
            name: string;
        };
        /** Reason */
        Reason: {
            /** Id */
            id?: number | null;
            /** Text */
            text: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** SearchHit */
        SearchHit: {
            /** Label Id */
            label_id: number;
            /** Discipline Id */
            discipline_id: number;
            /** Discipline Name */
            discipline_name: string;
            /** Project Name */
            project_name: string;
            /** Data Hall Name */
            data_hall_name: string;
            /** Sheet Name */
            sheet_name: string;
            /** Row Idx */
            row_idx: number;
            /** Left Text */
            left_text: string;
            /** Right Text */
            right_text: string;
            /** Matched Left */
            matched_left: boolean;
            /** Matched Right */
            matched_right: boolean;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Expanded */
            expanded: string[];
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /** Total */
            total: number;
        };
        /**
         * Template
         * @description Reusable print config — references a printer; configures bitmap rendering.
         *
         *     Field names match the Android app's ``PrintSettings`` (and the on-disk
         *     ``PANDUIT_TEMPLATE_EXPORT_V1`` order in ``default_templates.txt``):
         *     each ``*_top``/``*_bottom``/``*_left``/``*_right`` is one **edge** of
         *     that text rectangle (not x/y/width/height).
         */
        Template: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
            /** Printer Id */
            printer_id: number;
            /** Bytes Per Row */
            bytes_per_row: number;
            /** Height */
            height: number;
            /**
             * Left Top
             * @default 0
             */
            left_top: number;
            /**
             * Left Bottom
             * @default 0
             */
            left_bottom: number;
            /**
             * Left Left
             * @default 0
             */
            left_left: number;
            /**
             * Left Right
             * @default 0
             */
            left_right: number;
            /**
             * Right Top
             * @default 0
             */
            right_top: number;
            /**
             * Right Bottom
             * @default 0
             */
            right_bottom: number;
            /**
             * Right Left
             * @default 0
             */
            right_left: number;
            /**
             * Right Right
             * @default 0
             */
            right_right: number;
            /**
             * Gap Top
             * @default 0
             */
            gap_top: number;
            /**
             * Gap Bottom
             * @default 0
             */
            gap_bottom: number;
            /**
             * Gap Left
             * @default 0
             */
            gap_left: number;
            /**
             * Gap Right
             * @default 0
             */
            gap_right: number;
            /**
             * Left Text
             * @default TEXT+12345
             */
            left_text: string;
            /**
             * Right Text
             * @default TEXT+12345
             */
            right_text: string;
            /**
             * Left Pt
             * @default 7
             */
            left_pt: number;
            /**
             * Right Pt
             * @default 7
             */
            right_pt: number;
            /** @default CENTER */
            h_align: components["schemas"]["HAlign"];
            /** @default CENTER */
            v_align: components["schemas"]["VAlign"];
            /**
             * Font Name
             * @default Microsoft Sans Serif
             */
            font_name: string;
            /**
             * Font Style
             * @default Bold
             */
            font_style: string;
            /**
             * Left Offset
             * @default 0
             */
            left_offset: number;
            /**
             * Right Offset
             * @default 0
             */
            right_offset: number;
            /**
             * Mirror Mode
             * @default false
             */
            mirror_mode: boolean;
        };
        /**
         * VAlign
         * @enum {string}
         */
        VAlign: "TOP" | "CENTER" | "BOTTOM";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_printers_api_printers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Printer"][];
                };
            };
        };
    };
    create_printer_api_printers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Printer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Printer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ping_all_api_printers_ping_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResult"][];
                };
            };
        };
    };
    get_printer_api_printers__printer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Printer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_printer_api_printers__printer_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Printer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Printer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_printer_api_printers__printer_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ping_api_printers__printer_id__ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"][];
                };
            };
        };
    };
    create_template_api_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Template"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_templates__template_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Template"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_halls_api_halls_get: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataHall"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_hall_api_halls_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataHall"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_hall_api_halls__hall_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hall_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_disciplines_api_disciplines_get: {
        parameters: {
            query?: {
                data_hall_id?: number | null;
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisciplineDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_discipline_api_disciplines_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisciplineIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Discipline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_discipline_api_disciplines__discipline_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discipline_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisciplinePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Discipline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_discipline_api_disciplines__discipline_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discipline_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reasons_api_reasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reason"][];
                };
            };
        };
    };
    create_reason_api_reasons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reason"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reason"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reason_api_reasons__reason_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reason_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_auth_api_auth_names_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthName"][];
                };
            };
        };
    };
    create_auth_api_auth_names_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthName"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthName"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_auth_api_auth_names__auth_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auth_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_api_labels_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_api_labels_search_get: {
        parameters: {
            query: {
                /** @description cable id, text, range '45.5-7' or list '45.5,6,7' */
                q: string;
                project_id?: number | null;
                data_hall_id?: number | null;
                discipline_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_api_import_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_scan_api_import_scan_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_import_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_import_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_imports_api_imports_get: {
        parameters: {
            query?: {
                discipline_id?: number | null;
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_import_api_imports__import_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cart_api_cart_get: {
        parameters: {
            query: {
                sid: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartItemDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_cart_api_cart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartItemDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cart_api_cart_delete: {
        parameters: {
            query: {
                sid: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_item_api_cart__item_id__delete: {
        parameters: {
            query: {
                sid: string;
            };
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    print_all_api_cart_print_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrintAllRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrintAllResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_print_preview_get: {
        parameters: {
            query?: {
                template_id?: number | null;
                label_id?: number | null;
                left_text?: string;
                right_text?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_print_api_print_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_api_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrintLog"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    admin_admin_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
