"""add Import table and Label.import_id

Revision ID: 232e2ff8080e
Revises: eb677bd2f0fc
Create Date: 2026-05-20 20:03:27.269443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  — autogen emits ``sqlmodel.sql.sqltypes.AutoString``


# revision identifiers, used by Alembic.
revision: str = '232e2ff8080e'
down_revision: Union[str, Sequence[str], None] = 'eb677bd2f0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('sheets', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_discipline_id'), ['discipline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_uploaded_at'), ['uploaded_at'], unique=False)

    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_label_import_id'), ['import_id'], unique=False)
        batch_op.create_foreign_key('fk_label_import_id', 'import', ['import_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_constraint('fk_label_import_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_label_import_id'))
        batch_op.drop_column('import_id')

    with op.batch_alter_table('import', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_import_discipline_id'))

    op.drop_table('import')
    # ### end Alembic commands ###
