"""add printer protocol

Revision ID: c886c484ba4c
Revises: c3e8f1a2045b
Create Date: 2026-05-28 09:51:54.026473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  — autogen emits ``sqlmodel.sql.sqltypes.AutoString``


# revision identifiers, used by Alembic.
revision: str = 'c886c484ba4c'
down_revision: Union[str, Sequence[str], None] = 'c3e8f1a2045b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default keeps existing rows NOT NULL — they're all TSC TDP-43ME, so
    # 'epl2' is the right backfill. Future rows get their default from the SQLModel
    # field declaration, not the DB.
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'protocol',
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default='epl2',
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.drop_column('protocol')

    # ### end Alembic commands ###
