"""initial schema

Revision ID: eb677bd2f0fc
Revises: 
Create Date: 2026-05-20 19:27:12.969260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  — autogen emits ``sqlmodel.sql.sqltypes.AutoString``


# revision identifiers, used by Alembic.
revision: str = 'eb677bd2f0fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('printer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('printlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('printer_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('left_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('right_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('printlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_printlog_ts'), ['ts'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('datahall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    with op.batch_alter_table('datahall', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datahall_project_id'), ['project_id'], unique=False)

    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('bytes_per_row', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('left_top', sa.Float(), nullable=False),
    sa.Column('left_bottom', sa.Float(), nullable=False),
    sa.Column('left_left', sa.Float(), nullable=False),
    sa.Column('left_right', sa.Float(), nullable=False),
    sa.Column('right_top', sa.Float(), nullable=False),
    sa.Column('right_bottom', sa.Float(), nullable=False),
    sa.Column('right_left', sa.Float(), nullable=False),
    sa.Column('right_right', sa.Float(), nullable=False),
    sa.Column('gap_top', sa.Float(), nullable=False),
    sa.Column('gap_bottom', sa.Float(), nullable=False),
    sa.Column('gap_left', sa.Float(), nullable=False),
    sa.Column('gap_right', sa.Float(), nullable=False),
    sa.Column('left_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('right_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('left_pt', sa.Float(), nullable=False),
    sa.Column('right_pt', sa.Float(), nullable=False),
    sa.Column('h_align', sa.Enum('LEFT', 'CENTER', 'RIGHT', name='halign'), nullable=False),
    sa.Column('v_align', sa.Enum('TOP', 'CENTER', 'BOTTOM', name='valign'), nullable=False),
    sa.Column('font_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('font_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('left_offset', sa.Float(), nullable=False),
    sa.Column('right_offset', sa.Float(), nullable=False),
    sa.Column('mirror_mode', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hall_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['data_hall_id'], ['datahall.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_hall_id', 'name')
    )
    with op.batch_alter_table('discipline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discipline_data_hall_id'), ['data_hall_id'], unique=False)

    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_file', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row_idx', sa.Integer(), nullable=False),
    sa.Column('left_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('right_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_label_discipline_id'), ['discipline_id'], unique=False)

    op.create_table('cartitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('left_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('right_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cartitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cartitem_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cartitem_session_id'))

    op.drop_table('cartitem')
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_label_discipline_id'))

    op.drop_table('label')
    with op.batch_alter_table('discipline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discipline_data_hall_id'))

    op.drop_table('discipline')
    op.drop_table('template')
    with op.batch_alter_table('datahall', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datahall_project_id'))

    op.drop_table('datahall')
    op.drop_table('reason')
    op.drop_table('project')
    with op.batch_alter_table('printlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_printlog_ts'))

    op.drop_table('printlog')
    op.drop_table('printer')
    op.drop_table('authname')
    # ### end Alembic commands ###
